// @ts-check

import { incrementTickQueuque } from '../componentStore/tick';
import { QUEQUE_TYPE_PARSE_WATCH_ASYNC } from '../constant';
import { MAIN_STORE_REPEATER_PARSER_ROOT } from '../mainStore/constant';
import { mainStore } from '../mainStore/mainStore';
import { incrementParserCounter } from '../temporaryData/parser/parser';
import { parseComponentsRecursive } from './parseComponentRecursive';

/**
 * @param {object} obj
 * @param {HTMLElement} obj.element
 * @param {boolean} [ obj.isCancellable ]
 * @param {string} [ obj.parentIdForced ]
 * @return {Promise<void>} A promise to the token.
 *
 * @description
 */
export const parseComponents = async ({
    element,
    isCancellable = true,
    parentIdForced,
}) => {
    incrementParserCounter();

    await parseComponentsRecursive({
        element,
        isCancellable,
        currentIterationCounter: 0,
        parentIdForced,
    });
};

/**
 * @description
 * Parse component from inner component generated by first parseComponent.
 * Use pub/sub to avoid circular dependencies.
 *
 * @returns {void}
 */
export const initParseWatcher = () => {
    mainStore.watch(
        MAIN_STORE_REPEATER_PARSER_ROOT,
        async ({ element, parentId }) => {
            const decrementQueqe = incrementTickQueuque({
                element,
                type: QUEQUE_TYPE_PARSE_WATCH_ASYNC,
            });

            await parseComponents({
                element,
                parentIdForced: parentId,
            });

            decrementQueqe();
        }
    );
};

/**
 * @param {HTMLElement} element
 * @return {Promise<void>} A promise to the token.
 *
 * @description
 */
export const parseDom = async (element) => {
    await parseComponents({
        element,
    });
};
