// @ts-check

import { incrementParserCounter } from '../mainStore/actions/parser';
import { mainStore } from '../mainStore/mainStore';
import { parseComponentsRecursive } from './parseComponentRecursive';

/**
 * @param {Object} obj
 * @param {HTMLElement} obj.element
 * @param {string|null} [ obj.runtimeId ]
 * @return {Promise<void>} A promise to the token.
 *
 * @description
 */
export const parseComponents = async ({ element, runtimeId = null }) => {
    incrementParserCounter();

    await parseComponentsRecursive({
        element,
        runtimeId,
    });
};

/**
 * @description
 * Parse component from inner component generated by first parseComponent.
 * Use pub/sub to avoid circular dependencies.
 */
mainStore.watch('parseComponentEvent', async ({ element, runtimeId }) => {
    await parseComponents({
        element,
        runtimeId,
    });
});
