import { pageNotFound } from './404';
import { layoutLinksPage } from './layout/layout-links';
import { layoutSidebarAnchor } from './layout/layout-sidebar-anchor';
import { layoutSidebarLinks } from './layout/layout-sidebar-links';
import { layoutAbout } from './about/layout-about';
import { benchMark } from './benchmark';
import { animatedPatternN0 } from './canvas/animated-pattern-n0';
import { animatedPatternN1 } from './canvas/animate-pattern-n1';
import { caterpillarN1 } from './canvas/caterpillar-n1';
import { caterpillarN2 } from './canvas/caterpillar-n2';
import { scrollerN0 } from './canvas/scroller';
import { scrollerN1 } from './canvas/scroller-n1';
import { dynamic_list } from './dynamic-list';
import { home } from './home';
import { matrioska_invalidate_page, matrioska_repeat_page } from './matrioska';
import { horizontalScroller } from './plugin/horizontal-scroller';
import { move3DRoute } from './plugin/move-3d';
import { move3DrouteProps } from './plugin/move-3d/props';
import { lettering01 } from './svg/mob-01';
import { asyncTimeline } from './canvas/async-timeline';
import { rdp } from './svg/rdp';
import { mob_02 } from './svg/mob-02';
import { DraggerRoute } from './plugin/dragger';
import { mathAnimationRoute } from './plugin/math-animation';
import { rosaDiGrandiRoute } from './plugin/rosa-di-grandi';

export const PAGE_TEMPLATE_HOME = 'home';
export const PAGE_TEMPLATE_ABOUT = 'about';
export const PAGE_TEMPLATE_COMPONENT_MOBJS = 'template-mobJs-component';
export const PAGE_TEMPLATE_DOCS_DEFAULT = 'template-doc-default';
export const PAGE_TEMPLATE_LINKS = 'template-listing';
export const PAGE_TEMPLATE_ONLY_DESKTOP = 'template-only-desktop';
export const PAGE_TEMPLATE_ANIMATION = 'template-animation';
export const PAGE_TEMPLATE_TEST = 'template-test';

export const docsTemplate = new Set([
    PAGE_TEMPLATE_COMPONENT_MOBJS,
    PAGE_TEMPLATE_DOCS_DEFAULT,
]);

/**
 * @type {import('@mobJsType').Route[]}
 */
export const routes = [
    {
        hash: 'pageNotFound',
        layout: pageNotFound,
        pageName: '404',
        props: {},
    },
    {
        hash: 'home',
        layout: home,
        templateName: PAGE_TEMPLATE_HOME,
        pageName: 'home',
        props: {},
    },
    {
        hash: 'about',
        layout: layoutAbout,
        templateName: PAGE_TEMPLATE_ABOUT,
        pageName: 'about us',
        props: {},
    },
    {
        hash: 'canvas-overview',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        pageName: 'canvas',
        props: {
            source: './data/canvas/data.json',
        },
    },
    {
        hash: 'animatedPatternN0',
        layout: animatedPatternN0,
        templateName: PAGE_TEMPLATE_ANIMATION,
        pageName: 'animatedPatternN0',
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'animatedPatternN1',
        layout: animatedPatternN1,
        templateName: PAGE_TEMPLATE_ANIMATION,
        pageName: 'animatedPatternN1',
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'caterpillarN1',
        layout: caterpillarN1,
        pageName: 'caterpillarN1',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'caterpillarN2',
        layout: caterpillarN2,
        pageName: 'caterpillarN2',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'async-timeline',
        layout: asyncTimeline,
        pageName: 'async timeline',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'scrollerN0',
        layout: scrollerN0,
        pageName: 'scrollerN0',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'scrollerN1',
        layout: scrollerN1,
        pageName: 'scrollerN1',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'dynamic-list',
        layout: dynamic_list,
        templateName: PAGE_TEMPLATE_TEST,
        pageName: 'dynamic list',
        skipTransition: true,
        props: {
            source: './data/mob-js/general-repeat-test.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'matrioska-repeat',
        layout: matrioska_repeat_page,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        pageName: 'matrioska repeat',
        props: {
            source: './data/mob-js/matrioska.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'matrioska-invalidate',
        layout: matrioska_invalidate_page,
        templateName: PAGE_TEMPLATE_TEST,
        pageName: 'matrioska invalidate',
        skipTransition: true,
        props: {
            source: './data/mob-js/matrioska.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-invalidate',
        pageName: 'mobJs benchmark invalidate',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-invalidate',
            source: './data/mob-js/benchmark-invalidate.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-key',
        pageName: 'mobJs benchmark repeat no key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-key',
            source: './data/mob-js/benchmark-repeat-without-key.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key',
        pageName: 'mobJs benchmark repeat key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key',
            source: './data/mob-js/benchmark-repeat-key.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-component-no-key',
        pageName: 'mobJs benchmark repeat no component no key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-component-no-key',
            source: './data/mob-js/benchmark-repeat-no-component-no-key.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-component-with-key',
        pageName: 'mobJs benchmark repeat no component with key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-component-with-key',
            source: './data/mob-js/benchmark-repeat-no-component-with-key.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-key-nested',
        pageName: 'mobJs benchmark repeat no key nested',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key-no-nested',
            source: './data/mob-js/benchmark-repeat-without-key-nested.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key-nested',
        pageName: 'mobJs benchmark repeat key nested',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key-nested',
            source: './data/mob-js/benchmark-repeat-key-nested.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key-bind-store',
        pageName: 'mobJs benchmark repeat key bind store',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-key-bind-store',
            source: './data/mob-js/benchmark-repeat-external.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobCore-overview',
        layout: layoutSidebarAnchor,
        skipTransition: true,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        pageName: 'mobCore',
        props: {
            source: './data/mob-core/overview.json',
            breadCrumbs: [],
            section: 'mobCore',
        },
    },
    {
        hash: 'mobCore-defaults',
        pageName: 'defaults',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/defaults.json',
            section: 'mobCore',
        },
    },
    {
        hash: 'mobCore-events',
        pageName: 'events',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/events.json',
            section: 'mobCore',
        },
    },
    {
        hash: 'mobCore-store',
        pageName: 'store',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/store.json',
            section: 'mobCore',
        },
    },
    {
        hash: 'mobJs-overview',
        pageName: 'mobJs',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        props: {
            source: './data/mob-js/overview.json',
            breadCrumbs: [],
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-initialization',
        pageName: 'initialization',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/initialization.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-component',
        pageName: 'component',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/component.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-routing',
        pageName: 'routing',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/routing.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-tick',
        pageName: 'tick',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/tick.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-utils',
        pageName: 'utils',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/utils.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-memory-management',
        pageName: 'memory management',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/memory-management.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-html-object',
        pageName: 'htmlObject',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/html-object.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-debug',
        pageName: 'debug',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/debug.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-onMount',
        pageName: 'onMount',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/on-mount.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-getState',
        pageName: 'getState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-state.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-setState',
        pageName: 'setState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/set-state.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-updateState',
        pageName: 'updateState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        parent: 'mobJs-component',
        skipTransition: true,
        props: {
            source: './data/mob-js/update-state.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-getProxi',
        pageName: 'getProxi',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-proxi.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-watch',
        pageName: 'watch',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/watch.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-staticProps',
        pageName: 'staticProps',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/static-props.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-dataAttribute',
        pageName: 'dataAttribute',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/data-attribute.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bindProps',
        pageName: 'bindProps',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-props.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bindEvents',
        pageName: 'bindEvents',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-events.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-delegateEvents',
        pageName: 'delegateEvents',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/delegate-events.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bindtext',
        pageName: 'bindText',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-text.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bindObject',
        pageName: 'bindObject',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-object.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bind-effect',
        pageName: 'bindEffect',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-effect.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-methods',
        pageName: 'methods',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/methods.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-useMethodByName',
        pageName: 'useMethodByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/use-method-by-name.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-useMethodArrayByName',
        pageName: 'useMethodArrayByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/use-method-array-by-name.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-setStateByName',
        pageName: 'setStateByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/set-state-by-name.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-updateStateByName',
        pageName: 'updateStateByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/update-state-by-name.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-refs',
        pageName: 'refs',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/refs.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-runtime',
        pageName: 'runtime',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/runtime.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-repeat',
        pageName: 'repeat',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/repeat.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-invalidate',
        pageName: 'invalidate',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/invalidate.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-invalidate-vs-repeater',
        pageName: 'invalidate vs repeater',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/invalidate-vs-repeater.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-web-component',
        pageName: 'webComponent',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/web-component.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-slot',
        pageName: 'slot',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/slot.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-unBind',
        pageName: 'unBind',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/unbind.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-emit',
        pageName: 'emit',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/emit.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-emitAsync',
        pageName: 'emitAsync',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/emit-async.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-computed',
        pageName: 'computed',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/computed.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-bindStore',
        pageName: 'bindStore',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-store.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-removeDom',
        pageName: 'removeDom',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/remove-dom.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-remove',
        pageName: 'remove',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/remove.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-getChildren',
        pageName: 'getChildren',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-children.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-freezeProp',
        pageName: 'freezeProp',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/freeze-prop.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-unFreezeProp',
        pageName: 'unFreezeProp',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/unfreeze-prop.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-getParentId',
        pageName: 'getParentId',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-parent-id.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-watchParent',
        pageName: 'watchParent',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/watch-parent.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-instanceName',
        pageName: 'instanceName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/instance-name.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-class-list',
        pageName: 'classList',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/class-list.json',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobMotion-overview',
        pageName: 'mobMotion',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        props: {
            source: './data/mob-motion/overview.json',
            breadCrumbs: [],
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-stagger',
        pageName: 'stagger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/stagger.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-defaults',
        pageName: 'defaults',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/defaults.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-utils',
        pageName: 'utils',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/utils.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-parallax',
        pageName: 'parallax',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/parallax.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-sequencer',
        pageName: 'sequencer',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/sequencer.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-scrolltrigger',
        pageName: 'scrolltrigger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/scroll-trigger.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-sync-timeline',
        pageName: 'syncTimeline',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/sync-timeline.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-create-stagger',
        pageName: 'createStagger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/create-stagger.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-async-timeline',
        pageName: 'asyncTimeline',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/async-timeline.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'mobMotion-tween-spring-lerp',
        pageName: 'tween/spring/lerp',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/tween-spring-lerp.json',
            section: 'mobMotion',
        },
    },
    {
        hash: 'horizontalScroller',
        pageName: 'horizontalScroller',
        layout: horizontalScroller,
        templateName: PAGE_TEMPLATE_ANIMATION,
        restoreScroll: false,
        parent: 'mobMotion-overview',
        props: {
            source: './data/plugin/horizontal-scroller.json',
        },
    },
    {
        hash: 'plugin-overview',
        pageName: 'plugin',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        props: {
            source: './data/plugin/data.json',
        },
    },
    {
        hash: 'move3D-shape1',
        pageName: 'move3D',
        templateName: PAGE_TEMPLATE_ANIMATION,
        layout: move3DRoute,
        parent: 'plugin-overview',
        props: move3DrouteProps.shape1,
    },
    {
        hash: 'plugin-dragger',
        pageName: 'dragger',
        layout: DraggerRoute,
        parent: 'plugin-overview',
        templateName: PAGE_TEMPLATE_ANIMATION,
        props: {},
    },
    {
        hash: 'math-animation-01',
        pageName: 'math animation 01',
        layout: mathAnimationRoute,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'plugin-overview',
        props: {
            names: ['circle', 'sin', 'infinite', 'archimede'],
        },
    },
    {
        hash: 'rosa-di-grandi',
        pageName: 'rosa di grandi',
        layout: rosaDiGrandiRoute,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'plugin-overview',
        props: {},
    },
    {
        hash: 'svg-overview',
        pageName: 'svg',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        props: {
            source: './data/svg/data.json',
        },
    },
    {
        hash: 'mob-01',
        pageName: 'mob 01',
        layout: lettering01,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
    {
        hash: 'mob-02',
        pageName: 'mob 02',
        layout: mob_02,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
    {
        hash: 'rdp-01',
        pageName: 'rdp 01',
        layout: rdp,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
];
