import { pageNotFound } from './404';
import { layoutLinksPage } from './layout/layout-links';
import { layoutSidebarAnchor } from './layout/layout-sidebar-anchor';
import { layoutSidebarLinks } from './layout/layout-sidebar-links';
import { layoutAbout } from './about/layout-about';
import { benchMark } from './benchmark';
import { animatedPatternN0 } from './canvas/animated-pattern-n0';
import { animatedPatternN1 } from './canvas/animate-pattern-n1';
import { caterpillarN1 } from './canvas/caterpillar-n1';
import { caterpillarN2 } from './canvas/caterpillar-n2';
import { scrollerN0 } from './canvas/scroller';
import { scrollerN1 } from './canvas/scroller-n1';
import { dynamic_list } from './dynamic-list';
import { home } from './home';
import { matrioska_invalidate_page, matrioska_repeat_page } from './matrioska';
import { horizontalScroller } from './plugin/horizontal-scroller';
import { move3DRoute } from './plugin/move-3d';
import { move3DrouteProps } from './plugin/move-3d/props';
import { lettering01 } from './svg/mob-01';
import { asyncTimeline } from './canvas/async-timeline';
import { rdp } from './svg/rdp';
import { mob_02 } from './svg/mob-02';
import { DraggerRoute } from './plugin/dragger';
import { mathAnimationRoute } from './plugin/math-animation';
import { rosaDiGrandiRoute } from './plugin/rosa-di-grandi';

export const PAGE_TEMPLATE_HOME = 'home';
export const PAGE_TEMPLATE_ABOUT = 'about';
export const PAGE_TEMPLATE_COMPONENT_MOBJS = 'template-mobJs-component';
export const PAGE_TEMPLATE_DOCS_DEFAULT = 'template-doc-default';
export const PAGE_TEMPLATE_LINKS = 'template-listing';
export const PAGE_TEMPLATE_ONLY_DESKTOP = 'template-only-desktop';
export const PAGE_TEMPLATE_ANIMATION = 'template-animation';
export const PAGE_TEMPLATE_TEST = 'template-test';

export const docsTemplate = new Set([
    PAGE_TEMPLATE_COMPONENT_MOBJS,
    PAGE_TEMPLATE_DOCS_DEFAULT,
]);

const mobJsComponentBreadCrumbs = [
    {
        url: './#mobJs-overview',
        title: 'mobJs',
    },
    {
        url: './#mobJs-component',
        title: 'component',
    },
];

const mobJsOverviewBreadCrumbs = [
    {
        url: './#mobJs-overview',
        title: 'mobJs',
    },
];

const mobCoreOverviewBreadCrumbs = [
    {
        url: './#mobCore-overview',
        title: 'mobCore',
    },
];

const mobMotionOverviewBreadCrumbs = [
    {
        url: './#mobMotion-overview',
        title: 'mobMotion',
    },
];

const mobCoreLeftSidebar = [
    {
        label: 'store',
        url: '#mobCore-store',
        children: [],
    },
    {
        label: 'events',
        url: '#mobCore-events',
        children: [],
    },
    {
        label: 'defaults',
        url: '#mobCore-defaults',
        children: [],
    },
];

const mobJsLeftSidebar = [
    {
        label: 'initialization',
        url: '#mobJs-initialization',
        children: [],
    },
    {
        label: 'component',
        url: '#mobJs-component',
        children: [
            '#mobJs-onMount',
            '#mobJs-getProxi',
            '#mobJs-getState',
            '#mobJs-setState',
            '#mobJs-updateState',
            '#mobJs-computed',
            '#mobJs-bindStore',
            '#mobJs-watch',
            '#mobJs-dataAttribute',
            '#mobJs-staticProps',
            '#mobJs-bindProps',
            '#mobJs-bindtext',
            '#mobJs-bindObject',
            '#mobJs-bind-effect',
            '#mobJs-refs',
            '#mobJs-bindEvents',
            '#mobJs-delegateEvents',
            '#mobJs-instanceName',
            '#mobJs-methods',
            '#mobJs-useMethodByName',
            '#mobJs-useMethodArrayByName',
            '#mobJs-setStateByName',
            '#mobJs-updateStateByName',
            '#mobJs-runtime',
            '#mobJs-invalidate',
            '#mobJs-repeat',
            '#mobJs-invalidate-vs-repeater',
            '#mobJs-web-component',
            '#mobJs-slot',
            '#mobJs-class-list',
            '#mobJs-unBind',
            '#mobJs-emit',
            '#mobJs-emitAsync',
            '#mobJs-removeDom',
            '#mobJs-remove',
            '#mobJs-getChildren',
            '#mobJs-freezeProp',
            '#mobJs-unFreezeProp',
            '#mobJs-getParentId',
            '#mobJs-watchParent',
        ],
    },
    {
        label: 'htmlObject',
        url: '#mobJs-html-object',
        children: [],
    },
    {
        label: 'routing',
        url: '#mobJs-routing',
        children: [],
    },
    {
        label: 'tick',
        url: '#mobJs-tick',
        children: [],
    },
    {
        label: 'memory management',
        url: '#mobJs-memory-management',
        children: [],
    },
    {
        label: 'utils',
        url: '#mobJs-utils',
        children: [],
    },
    {
        label: 'debug',
        url: '#mobJs-debug',
        children: [],
    },
];

const mobMotionLeftSidebar = [
    {
        label: 'tween/spring/lerp',
        url: '#mobMotion-tween-spring-lerp',
        children: [],
    },
    {
        label: 'AsyncTimeline',
        url: '#mobMotion-async-timeline',
        children: [],
    },
    {
        label: 'sequencer',
        url: '#mobMotion-sequencer',
        children: [],
    },
    {
        label: 'SyncTimeline',
        url: '#mobMotion-sync-timeline',
        children: [],
    },
    {
        label: 'CreateStagger',
        url: '#mobMotion-create-stagger',
        children: [],
    },
    {
        label: 'ScrollTrigger',
        url: '#mobMotion-scrolltrigger',
        children: [],
    },
    {
        label: 'Parallax',
        url: '#mobMotion-parallax',
        children: [],
    },
    {
        label: 'Stagger',
        url: '#mobMotion-stagger',
        children: [],
    },
    {
        label: 'Default',
        url: '#mobMotion-defaults',
        children: [],
    },
    {
        label: 'Utils',
        url: '#mobMotion-utils',
        children: [],
    },
];

/**
 * @type {import('@mobJsType').Route[]}
 */
export const routes = [
    {
        hash: 'pageNotFound',
        layout: pageNotFound,
        pageName: 'page not found',
        props: {},
    },
    {
        hash: 'home',
        layout: home,
        templateName: PAGE_TEMPLATE_HOME,
        pageName: 'home',
        props: {},
    },
    {
        hash: 'about',
        layout: layoutAbout,
        templateName: PAGE_TEMPLATE_ABOUT,
        pageName: 'about us',
        props: {},
    },
    {
        hash: 'canvas-overview',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        pageName: 'canvas overview',
        props: {
            source: './data/canvas/data.json',
        },
    },
    {
        hash: 'animatedPatternN0',
        layout: animatedPatternN0,
        templateName: PAGE_TEMPLATE_ANIMATION,
        pageName: 'animatedPatternN0',
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'animatedPatternN1',
        layout: animatedPatternN1,
        templateName: PAGE_TEMPLATE_ANIMATION,
        pageName: 'animatedPatternN1',
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'caterpillarN1',
        layout: caterpillarN1,
        pageName: 'caterpillarN1',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'caterpillarN2',
        layout: caterpillarN2,
        pageName: 'caterpillarN2',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'async-timeline',
        layout: asyncTimeline,
        pageName: 'async timeline',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'scrollerN0',
        layout: scrollerN0,
        pageName: 'scrollerN0',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'scrollerN1',
        layout: scrollerN1,
        pageName: 'scrollerN1',
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'canvas-overview',
        props: {},
    },
    {
        hash: 'dynamic-list',
        layout: dynamic_list,
        templateName: PAGE_TEMPLATE_TEST,
        pageName: 'dynamic list',
        skipTransition: true,
        props: {
            source: './data/mob-js/general-repeat-test.json',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            title: '( test ) repeat & invalidate',
            section: 'mobJs',
        },
    },
    {
        hash: 'matrioska-repeat',
        layout: matrioska_repeat_page,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        pageName: 'matrioska repeat',
        props: {
            source: './data/mob-js/matrioska.json',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            title: '( test ) matrioska repeat',
            section: 'mobJs',
        },
    },
    {
        hash: 'matrioska-invalidate',
        layout: matrioska_invalidate_page,
        templateName: PAGE_TEMPLATE_TEST,
        pageName: 'matrioska invalidate',
        skipTransition: true,
        props: {
            source: './data/mob-js/matrioska.json',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            title: '( test ) matrioska invalidate',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-invalidate',
        pageName: 'mobJs benchmark invalidate',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-invalidate',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-invalidate.json',
            title: '( test ) benchmark invalidate',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-key',
        pageName: 'mobJs benchmark repeat no key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-key',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-without-key.json',
            title: '( test ) benchmark repeat without key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key',
        pageName: 'mobJs benchmark repeat key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-key.json',
            title: '( test ) benchmark repeat key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-component-no-key',
        pageName: 'mobJs benchmark repeat no component no key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-component-no-key',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-no-component-no-key.json',
            title: '( test ) benchmark repeat no component no key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-component-with-key',
        pageName: 'mobJs benchmark repeat no component with key',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-component-with-key',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-no-component-with-key.json',
            title: '( test ) benchmark repeat no component with key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-no-key-nested',
        pageName: 'mobJs benchmark repeat no key nested',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key-no-nested',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-without-key-nested.json',
            title: '( test ) benchmark repeat nested without key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key-nested',
        pageName: 'mobJs benchmark repeat key nested',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-key-nested',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-key-nested.json',
            title: '( test ) benchmark repeat nested with key',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobJs-benchmark-repeat-key-bind-store',
        pageName: 'mobJs benchmark repeat key bind store',
        layout: benchMark,
        templateName: PAGE_TEMPLATE_TEST,
        skipTransition: true,
        props: {
            rootComponent: 'benchmark-repeat-no-key-bind-store',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            source: './data/mob-js/benchmark-repeat-external.json',
            title: '( test ) benchmark repeat bindStore',
            section: 'mobJs',
        },
    },
    {
        hash: 'mobCore-overview',
        layout: layoutSidebarAnchor,
        skipTransition: true,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        pageName: 'mobCore overview',
        props: {
            source: './data/mob-core/overview.json',
            title: 'mobCore',
            breadCrumbs: [],
            section: 'mobCore',
            leftSidebar: mobCoreLeftSidebar,
        },
    },
    {
        hash: 'mobCore-defaults',
        pageName: 'mobCore defaults',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/defaults.json',
            title: 'Defaults',
            breadCrumbs: mobCoreOverviewBreadCrumbs,
            section: 'mobCore',
            leftSidebar: mobCoreLeftSidebar,
        },
    },
    {
        hash: 'mobCore-events',
        pageName: 'mobCore events',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/events.json',
            title: 'Events',
            breadCrumbs: mobCoreOverviewBreadCrumbs,
            section: 'mobCore',
            leftSidebar: mobCoreLeftSidebar,
        },
    },
    {
        hash: 'mobCore-store',
        pageName: 'mobCore store',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobCore-overview',
        props: {
            source: './data/mob-core/store.json',
            title: 'Store',
            breadCrumbs: mobCoreOverviewBreadCrumbs,
            section: 'mobCore',
            leftSidebar: mobCoreLeftSidebar,
        },
    },
    {
        hash: 'mobJs-overview',
        pageName: 'mobJs overview',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        props: {
            source: './data/mob-js/overview.json',
            title: 'mobJs',
            breadCrumbs: [],
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-initialization',
        pageName: 'mobJs initialization',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/initialization.json',
            title: 'initialization',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-component',
        pageName: 'mobJs component',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/component.json',
            title: 'component',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-routing',
        pageName: 'mobJs routing',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/routing.json',
            title: 'routing',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-tick',
        pageName: 'mobJs tick',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/tick.json',
            title: 'tick',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-utils',
        pageName: 'mobJs utils',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/utils.json',
            title: 'utils',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-memory-management',
        pageName: 'mobJs memory management',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/memory-management.json',
            title: 'memory management',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-html-object',
        pageName: 'mobJs html object',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/html-object.json',
            title: 'htmlObject',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-debug',
        pageName: 'mobJs debug',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobJs-overview',
        props: {
            source: './data/mob-js/debug.json',
            title: 'debug',
            breadCrumbs: mobJsOverviewBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-onMount',
        pageName: 'mobJs onMount',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/on-mount.json',
            title: 'onMount',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-getState',
        pageName: 'mobJs getState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-state.json',
            title: 'getState',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-setState',
        pageName: 'mobJs setState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/set-state.json',
            title: 'setState',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-updateState',
        pageName: 'mobJs updateState',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        parent: 'mobJs-component',
        skipTransition: true,
        props: {
            source: './data/mob-js/update-state.json',
            title: 'updateState',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-getProxi',
        pageName: 'mobJs getProxi',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-proxi.json',
            title: 'getProxi',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-watch',
        pageName: 'mobJs watch',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/watch.json',
            title: 'watch',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-staticProps',
        pageName: 'mobJs staticProps',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/static-props.json',
            title: 'staticProps',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-dataAttribute',
        pageName: 'mobJs dataAttribute',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/data-attribute.json',
            title: 'dataAttribute',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bindProps',
        pageName: 'mobJs bindProps',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-props.json',
            title: 'bindProps',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bindEvents',
        pageName: 'mobJs bindEvents',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-events.json',
            title: 'bindEvents',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-delegateEvents',
        pageName: 'mobJs delegateEvents',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/delegate-events.json',
            title: 'delegateEvents',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bindtext',
        pageName: 'mobJs bindtext',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-text.json',
            title: 'bindText',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bindObject',
        pageName: 'mobJs bindObject',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-object.json',
            title: 'bindObject',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bind-effect',
        pageName: 'mobJs bind effect',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-effect.json',
            title: 'bindEffect',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-methods',
        pageName: 'mobJs methods',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/methods.json',
            title: 'add methods',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-useMethodByName',
        pageName: 'mobJs useMethodByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/use-method-by-name.json',
            title: 'useMethodByName',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-useMethodArrayByName',
        pageName: 'mobJs useMethodArrayByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/use-method-array-by-name.json',
            title: 'useMethodArrayByName',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-setStateByName',
        pageName: 'mobJs setStateByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/set-state-by-name.json',
            title: 'setStateByName',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-updateStateByName',
        pageName: 'mobJs updateStateByName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/update-state-by-name.json',
            title: 'updateStateByName',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-refs',
        pageName: 'mobJs refs',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/refs.json',
            title: 'refs',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-runtime',
        pageName: 'mobJs runtime',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/runtime.json',
            title: 'renderComponent',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-repeat',
        pageName: 'mobJs repeat',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/repeat.json',
            title: 'repeat',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-invalidate',
        pageName: 'mobJs invalidate',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/invalidate.json',
            title: 'invalidate',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-invalidate-vs-repeater',
        pageName: 'mobJs invalidate vs repeater',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/invalidate-vs-repeater.json',
            title: 'invalidate vs repeater',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-web-component',
        pageName: 'mobJs web component',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/web-component.json',
            title: 'webComponent',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-slot',
        pageName: 'mobJs slot',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/slot.json',
            title: 'slot',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-unBind',
        pageName: 'mobJs unBind',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/unbind.json',
            title: 'unBind',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-emit',
        pageName: 'mobJs emit',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/emit.json',
            title: 'emit',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-emitAsync',
        pageName: 'mobJs emitAsync',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/emit-async.json',
            title: 'emitAsync',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-computed',
        pageName: 'mobJs computed',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/computed.json',
            title: 'computed',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-bindStore',
        pageName: 'mobJs bindStore',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/bind-store.json',
            title: 'bindStore',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-removeDom',
        pageName: 'mobJs removeDom',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/remove-dom.json',
            title: 'removeDom',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-remove',
        pageName: 'mobJs remove',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/remove.json',
            title: 'remove',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-getChildren',
        pageName: 'mobJs getChildren',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-children.json',
            title: 'getChildren',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-freezeProp',
        pageName: 'mobJs freezeProp',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/freeze-prop.json',
            title: 'freezeProp',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-unFreezeProp',
        pageName: 'mobJs unFreezeProp',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/unfreeze-prop.json',
            title: 'unFreezeProp',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-getParentId',
        pageName: 'mobJs getParentId',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/get-parent-id.json',
            title: 'getParentId',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-watchParent',
        pageName: 'mobJs watchParent',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/watch-parent.json',
            title: 'watchParent',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-instanceName',
        pageName: 'mobJs instanceName',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/instance-name.json',
            title: 'instanceName',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobJs-class-list',
        pageName: 'mobJs class list',
        templateName: PAGE_TEMPLATE_COMPONENT_MOBJS,
        layout: layoutSidebarLinks,
        skipTransition: true,
        parent: 'mobJs-component',
        props: {
            source: './data/mob-js/class-list.json',
            title: 'classList',
            breadCrumbs: mobJsComponentBreadCrumbs,
            section: 'mobJs',
            leftSidebar: mobJsLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-overview',
        pageName: 'mobMotion overview',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        props: {
            source: './data/mob-motion/overview.json',
            title: 'mobMotion',
            breadCrumbs: [],
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-stagger',
        pageName: 'mobMotion stagger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/stagger.json',
            title: 'Stagger',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-defaults',
        pageName: 'mobMotion defaults',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/defaults.json',
            title: 'Defaults',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-utils',
        pageName: 'mobMotion utils',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/utils.json',
            title: 'Utils',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-parallax',
        pageName: 'mobMotion parallax',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/parallax.json',
            title: 'Parallax',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-sequencer',
        pageName: 'mobMotion sequencer',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/sequencer.json',
            title: 'Sequencer',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-scrolltrigger',
        pageName: 'mobMotion scrolltrigger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/scroll-trigger.json',
            title: 'ScrollTrigger',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-sync-timeline',
        pageName: 'mobMotion sync timeline',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/sync-timeline.json',
            title: 'Synctimeline',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-create-stagger',
        pageName: 'mobMotion create stagger',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/create-stagger.json',
            title: 'CreateStagger',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-async-timeline',
        pageName: 'mobMotion async timeline',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/async-timeline.json',
            title: 'Asynctimeline',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'mobMotion-tween-spring-lerp',
        pageName: 'mobMotion tween spring lerp',
        layout: layoutSidebarAnchor,
        templateName: PAGE_TEMPLATE_DOCS_DEFAULT,
        skipTransition: true,
        parent: 'mobMotion-overview',
        props: {
            source: './data/mob-motion/tween-spring-lerp.json',
            title: 'TimeTween Spring Lerp',
            breadCrumbs: mobMotionOverviewBreadCrumbs,
            section: 'mobMotion',
            leftSidebar: mobMotionLeftSidebar,
        },
    },
    {
        hash: 'horizontalScroller',
        pageName: 'horizontalScroller',
        layout: horizontalScroller,
        templateName: PAGE_TEMPLATE_ANIMATION,
        restoreScroll: false,
        parent: 'mobMotion-overview',
        props: {
            source: './data/plugin/horizontal-scroller.json',
            title: 'HorizontalScroller',
        },
    },
    {
        hash: 'plugin-overview',
        pageName: 'plugin overview',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        props: {
            source: './data/plugin/data.json',
        },
    },
    {
        hash: 'move3D-shape1',
        pageName: 'move3D shape1',
        templateName: PAGE_TEMPLATE_ANIMATION,
        layout: move3DRoute,
        parent: 'plugin-overview',
        props: move3DrouteProps.shape1,
    },
    {
        hash: 'plugin-dragger',
        pageName: 'plugin dragger',
        layout: DraggerRoute,
        parent: 'plugin-overview',
        templateName: PAGE_TEMPLATE_ANIMATION,
        props: {},
    },
    {
        hash: 'math-animation-01',
        pageName: 'math animation 01',
        layout: mathAnimationRoute,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'plugin-overview',
        props: {
            names: ['circle', 'sin', 'infinite', 'archimede'],
        },
    },
    {
        hash: 'rosa-di-grandi',
        pageName: 'rosa di grandi',
        layout: rosaDiGrandiRoute,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'plugin-overview',
        props: {},
    },
    {
        hash: 'svg-overview',
        pageName: 'svg overview',
        layout: layoutLinksPage,
        templateName: PAGE_TEMPLATE_LINKS,
        props: {
            source: './data/svg/data.json',
        },
    },
    {
        hash: 'mob-01',
        pageName: 'mob 01',
        layout: lettering01,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
    {
        hash: 'mob-02',
        pageName: 'mob 02',
        layout: mob_02,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
    {
        hash: 'rdp-01',
        pageName: 'rdp 01',
        layout: rdp,
        templateName: PAGE_TEMPLATE_ANIMATION,
        parent: 'svg-overview',
        props: {},
    },
];
